### ISSUE TITLE
Migrate to mavenCentral()

### ISSUE THREAD

**Issue by jumaallan** [SafeBoda/android-commons#46]
Might be a great time to migrate the publishing to mavenCentral, since[ bintray is being shut down](https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/)

A great way to replace it would be by using this plugin - https://github.com/vanniktech/gradle-maven-publish-plugin

**Comment by jumaallan** [comment]
Seen the changes here actually - https://github.com/SafeBoda/android-commons/commit/ecc475e5e80e1829d32381d21c3f3d9ae0ad6356

**Comment by alaash-sb** [comment]
We have already moved to mavenCentral().
